server:
  address: localhost
  port: 8080
  servlet:
    contextPath: /api
  error:
    include-message: always

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active:
      - dev
  datasource:
    url: jdbc:h2:file:./data/credit-card-requests-records-v1-SNAPSHOT;mode=Oracle;INIT=RUNSCRIPT FROM 'src/main/resources/schema.sql'
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console.enabled: true

requests-folder: requests